import Head from 'next/head'
import CTASection from '../components/CTA/CTASection'
import FeaturesSection from '../components/FeaturesSection/Features'
import Footer from '../components/Footer/Footer'
import Hero from '../components/Hero/Hero'
import InfoSection from '../components/InfoSection/InfoSection'


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <InfoSection />
      <FeaturesSection />
      <CTASection />
      <Footer />
    </>
  )
}
